# feeder
feeder: st_gcn.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xview/val_data.npy
  label_path: ./data/NTU-RGB-D/xview/val_label.pkl

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25
  num_person: 2
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

# test 
phase: test
device: 0
test_batch_size: 64
weights: ./model/ntuxview-st_gcn.pt


