processor_cfg:
  type: "processor.pose_demo.inference"
  gpus: 1
  worker_per_gpu: 1
  video_file: resource/data_example/skateboarding.mp4
  save_dir: "work_dir/pose_demo"

  detection_cfg:
    model_cfg: configs/mmdet/cascade_rcnn_r50_fpn_1x.py
    checkpoint_file: mmskeleton://mmdet/cascade_rcnn_r50_fpn_20e
    bbox_thre: 0.8
  estimation_cfg:
    model_cfg: configs/pose_estimation/hrnet/pose_hrnet_w32_256x192_test.yaml
    checkpoint_file: mmskeleton://pose_estimation/pose_hrnet_w32_256x192
    data_cfg:
      image_size:
        - 192
        - 256
      pixel_std: 200
      image_mean:
        - 0.485
        - 0.456
        - 0.406
      image_std:
        - 0.229
        - 0.224
        - 0.225
      post_process: true

argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  video:
    bind_to: processor_cfg.video_file
    help: path to input video
  worker_per_gpu:
    bind_to: processor_cfg.worker_per_gpu
    help: number of workers for each gpu
  skeleton_model:
    bind_to: processor_cfg.estimation_cfg.model_cfg
  skeleton_checkpoint:
    bind_to: processor_cfg.estimation_cfg.checkpoint_file
  detection_model:
    bind_to: processor_cfg.detection_cfg.model_cfg
  detection_checkpoint:
    bind_to: processor_cfg.detection_cfg.checkpoint_file
