argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from

processor_cfg:
  type: "processor.recognition.test"
  workers: 16
  checkpoint: ./work_dir/recognition/st_gcn/dataset_example/latest.pth

  # model setting
  model_cfg:
    type: "models.backbones.ST_GCN_18"
    in_channels: 3
    num_class: 3
    edge_importance_weighting: True
    graph_cfg:
      layout: "coco"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    type: "datasets.DataPipeline"
    data_source:
      type: "datasets.SkeletonLoader"
      data_dir: ./data/dataset_example
      num_track: 2
      num_keypoints: 17
    pipeline:
      - { type: "datasets.skeleton.normalize_by_resolution" }
      - { type: "datasets.skeleton.mask_by_visibility" }
      - { type: "datasets.skeleton.pad_zero", size: 300 }
      - { type: "datasets.skeleton.random_crop", size: 300 }
      - { type: "datasets.skeleton.transpose", order: [0, 2, 1, 3] }
      - { type: "datasets.skeleton.to_tuple" }
  # dataloader setting
  batch_size: 3
  gpus: 1
